### ISSUE TITLE
Change "note-test/" to "channel/1/", and rename note_test.html template to channel.html

### ISSUE THREAD

**Issue by PeterCassetta** [CS3398-Arctic/CS3398-Arctic-F2016#75]

**Comment by uj00007** [comment]
hey i was looking into this issue can you tell me do you want "channel/1" specifically or the 1 should appear dynamically..? and fill in it some details regarding the project that would make it easier for me to figure out

**Comment by TristanThielemann** [comment]
Who are you exactly, and why does our local DNS think "http://www.jiithub.pe.hu" is virus.exe?

**Comment by uj00007** [comment]
i am from india ,btech pursuing student nope, its nothing related to virus,its my site hosted on hostinger ,my project actually for m college...

**Comment by PeterCassetta** [comment]
@uj00007 Hi, sorry for the misunderstanding. We're planning to have channel/1 appear dynamically eventually, but for now, we're just doing channel/1 statically.

For a little background on our project, check out our website, http://slamenotes.com.

This is our first Django project by the way, we're all students too. So while we will try to follow best practices, we will probably make some mistakes along the way. (So don't take our project as the "correct" way to do things.)

**Comment by uj00007** [comment]
@PeterCassetta no problem at all, i'll try my best to help..:)
